### ISSUE TITLE
An error in  ShotSegmentation::segmentSlidingWindows()

### ISSUE THREAD

**Issue by xiamenwcy** [Trojahn/FAST#2]
hello,I  read your code and found an error:
```
if (j >= 1)
					{
						shots.push_back(make_pair(ant,i - j));
						ant = i-j + 1; 
					}
					j = 0;
```
It should  be :
```
if (j >= 1)
					{
						shots.push_back(make_pair(ant,i - j));
						ant = i + 1; 
					}
					j = 0;
```
Because as you said  in https://github.com/Trojahn/FAST:
   If FAST detects a gradual transition such as swipe, fade in/out or other transition effect, the corresponding frames are discarted of the output CSV.  
  So, 'ant' shoule be updated in time as  'ant = i + 1; '

**Comment by Trojahn** [comment]
Hello!

Just tested with a Big Buck Bunny video (big_buck_bunny_480p_h264.mov) using default parameters and got the following segmentation:
1,8
9,21
22,33
34,41
42,285
286,378
379,393
394,416
417,420
421,432
433,477
478,553
554,604
...

With the proposed change, the output goes like that:
1,8
19,21
31,33
37,41
47,285
287,378
379,393
395,416
418,420
424,432
437,477
504,553
554,604
...

Although the first ones may be correct (there IS a gradual transition on the first frames of the video), the remaining seems odd: there are not any gradual transition aside from the first one, but almost all transitions are now detected as "gradual".

I can't be sure right now, but seems that this change breaks something along it. I'l try to rewrite the method to a simpler one in couple of days... Do you have any suggestion? :)

**Comment by Trojahn** [comment]
Just checked again and after some rewriting commited a fix. Indeed the index were being used incorrectly. Again, thanks for your report!

**Comment by xiamenwcy** [comment]
No thanks! your work is very useful for me!

**Comment by xiamenwcy** [comment]
Sorry,your lateset code has two issuses:
 1. 
```
double ShotSegmentation::calcThresholdIntersection(vector<double> distances, pair<int,int> window) {
	double avg = 0.0;
	
	for(int i = window.first; i < window.second; i++) {
		avg = avg + distances[i];
	}
	avg = avg / (double) (window.second - window.first);

	return avg * this->swIntersectThreshold;  ---->this->localSlidingWindowIntersectThreshold;
}

double ShotSegmentation::calcThresholdEuclidean(vector<double> distances, pair<int,int> window) {
	double avg = 0.0;
	
	for(int i = window.first; i < window.second; i++) {
		avg = avg + distances[i];
	}
	avg = avg / (double) (window.second - window.first);
	return avg * this->swEuclideanThreshold;----> this->localSlidingWindowEuclideanThreshold;
}
```
shouble be corrected  like  https://github.com/Trojahn/FAST/issues/1

2.  In ShotSegmentation::segmentSlidingWindows()

At end , we shoube add 
```
	if (shots.size()==0)
	{
		shots.push_back(make_pair(ant, window.second));
	}

```

**Comment by Trojahn** [comment]
Done!

Sorry for the mess :(
